### ISSUE TITLE
Persistent naming

### ISSUE THREAD

**Issue by acresp** [mcclurec/homebridge-volumio-speakers#6]
Hello,

It's not a "real" issue but an improvement request 🙂 

I'm using the plugin and I was thinking about the naming of each zones.
Actually, if I rename a zone, the "default" name is coming back after a homebridge restart.

For example, I have a zone which is "salle de bain" (bathroom), the default name after discovering is "Salle De Bain".
If I rename it to "Salle de bain" in the Home app, it will takes its default name after a homebridge restart.

It would be cool to be able to add each zone separately in the config, with a "persistent" name.

Kind regards

**Comment by mcclurec** [comment]
Ah, you're running in to this piece of code. https://github.com/mcclurec/homebridge-volumio-speakers/blob/master/src/utils.ts#L24-L30

My intent was for Homekit to just automatically get updated based on whatever the name of the zone is in Volumio. Unfortunately [the Volumio API](https://volumio.github.io/docs/API/WebSocket_APIs.html#page_Multiroom) returns the name of the zone with hyphens instead of spaces, and all lower case except for the first letter. For example, I named mine `Downstairs Speakers`. When I look in the "System -> Player Name" setting it shows up as `downstairs-speaker`. and when I retrieve it from the API, it comes through as `Downstairs-speaker`. 

I'll head over to the Volumio repo and see if I can't figure out what's going on with the way they save and broadcast zone names. Maybe I can prompt a change over there that would let me remove this pice of clean up code. I'll close this issue for now though.

**Comment by mcclurec** [comment]
Conversation over in the Volumio repo...
https://github.com/volumio/Volumio2/issues/2039

**Comment by acresp** [comment]
It follows what I read sometimes ago about the name which is also « dirty » on the shairport broadcasting. It’s the reason that I hardcoded the « pretty » names in the shairport config file of each of my zones 🙁
