### ISSUE TITLE
Force a playlist to start when enabling the "playing" state

### ISSUE THREAD

**Issue by acresp** [mcclurec/homebridge-volumio-speakers#7]
Hello,

I have an issue, but probably more related to Volumio than the plugin, but maybe it would be possible to "do something" to bypass it.

I have actually 4 Volumio zones, used mostly with Airplay devices, but I also made some ESP32 based circuit in my wall switchs to control the volume functions and play/stop. In that circuit, I force a play of a precise webradio.

The idea was to be able to force that webradio play through the play feature of the plugin.
But actually, If i run an airplay stream, stop it, the plugin play/stop function is useless, it plays nothing :/ 
Would it be possible to set a precise function for the play state (in that case: force a certain playlist or item to start).
In that case, I would be capable to play an airplay stream through my devices, or force a radio stream through the Home app.

Thanks for your help & work 🙂 

Kind regards

**Comment by mcclurec** [comment]
Hmmm... That could be interesting, but complicated. Thinking out load...

This plugin just takes whatever state Homekit sends, and passes it through to Volumio. I believe those states are usually Play and Pause, though there is a value for Stop. I'm just not sure if anything in Homekit actually sends that state.

It may be possible to do a check before sending the Play value to see if the Volumio server is in a Paused or Stopped state. If it's stopped, then it could send a different command first to load a playlist/web radio/whatever, then send the play command afterward. Not sure how much lag this would add to the interaction though. That would take some testing.

This might have a weird side effect on pausing/playing web radio though, since Volumio can't actually "pause" radio, but rather just stop it. Without doing some more testing, I'm not totally sure how it currently behaves given this post https://community.volumio.org/t/control-volumio-with-api-problem/12495/8

Any other thoughts? I'd love for this to just work like a regular Airplay target, but that is dependent on getting an open source Airplay 2 implementation working first. Speakers in Homekit only expose pause/play. Anything like media loading or even volume setting require Airplay

**Comment by mcclurec** [comment]
It's been a while, and this request is a little out of scope for what I was planning to do for this plugin. I'm going to close for now. Hopefully we get full AirPlay 2 control in the future.
